[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Solidity compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_limit = 9223372036854775807

# RPC settings
eth_rpc_url = "${RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# Deployment settings
broadcast = "broadcast"
private_key = "${PRIVATE_KEY}"

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/ds-test/src/"
]

# Cache settings
cache = true
cache_path = "cache"
force = false

# Formatter settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# Documentation settings
[doc]
out = "docs"
title = "MemeTWAP Documentation"