[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Solidity compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 3
gas_reports = ["*"]
gas_limit = 30000000

# RPC and API keys (commented out for local testing)
# eth_rpc_url = "${RPC_URL}"
# etherscan_api_key = "${ETHERSCAN_API_KEY}"
# private_key = "${PRIVATE_KEY}"

# Deployment settings
broadcast = "broadcast"
deployments = "deployments"

# Remappings for common libraries
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]

# Cache settings
cache = true
cache_path = "cache"
force = false

# Formatting
line_length = 100
tab_width = 4
bracket_spacing = true

# File system permissions
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" }
]

# Documentation settings
[doc]
out = "docs"
title = "MemeTWAP Documentation"