[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
script = "script"

# Solidity compiler settings
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "paris"

# Gas settings
gas_limit = 9223372036854775807
gas_price = 0

# Verbosity settings
verbosity = 2

# Test settings
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# RPC endpoints (can be configured later)
[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/YOUR_API_KEY"
localhost = "http://127.0.0.1:8545"

# Etherscan API keys (can be configured later)
[etherscan]
mainnet = { key = "YOUR_ETHERSCAN_API_KEY" }
sepolia = { key = "YOUR_ETHERSCAN_API_KEY" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
